language: node_js
node_js:
  - 12
deploy:
  - provider: script
    script: "./travis/deploy-prd.sh"
    on:
      tags: true
  - provider: script
    script: "./travis/deploy-stg.sh"
    on:
      branch: master
